name: PR check

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [ 'main' ]
    types: [ ready_for_review, opened, reopened, synchronize ]

permissions:
  contents: read
  packages: read
  # To report GitHub Actions status checks
  statuses: write

jobs:
  linting:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          # The super-linter needs the full git history to get the 
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter/slim@v6.8.0  # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_TERRAFORM_TERRASCAN: false # Either the super-linter/Terrascan is not using my config file
